apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realtime-chat-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: chat.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: realtime-chat-service
                port:
                  number: 80
